- DESCRIPTION
- app.R
- man/participant_metric_summary_tag_list.Rd
Addresses the first bullet of #125.
> Use dev qs to load old qs files.

- .github/workflows/test-coverage.yaml
- README.Rmd
- README.md
Duh, there's no benefit of running this if we aren't doing anything with it. We'll get in the habit of checking coverage, but let's keep it out of our main PRs.
Notes:
> No need to run this at all other than for main.

- .github/workflows/R-CMD-check-dev.yaml
- .github/workflows/R-CMD-check-main.yaml
Only run the full matrix on merge to main. Closes #135.
Notes:
> Fewer OS checks for dev.

- README.Rmd
- README.md
On main pkgdown site, link to main app; on dev site, link to dev app.
Notes:
> Link to app conditionally

- .github/workflows/shinyapps-deploy.yaml
- .github/workflows/shinyapps-terminate.yaml
Closes #167
Notes: 
This PR is pretty much self-reviewing 🙃
> Add a comment to PRs with deployment URL.

- .github/workflows/shinyapps-deploy.yaml
Try to cache the packages used for deployment, to speed up this very slow step.
Notes: 
I *think* I can test this by pushing an update and seeing how long the step takes... and by making sure the deployment doesn't break.
> Attempt to cache packages.

- README.md
Related to #181 (but only a half fix).
This needs to merge directly to main to fix the link on the "prod" pkgdown site.
Notes:
> Correct link on prod pkgdown site.

- README.Rmd
- README.md
Correct link to shinyapps.io for prod (once we merge to main with a new deployment) and dev.
Closes #181.
Notes:
> Dotless links for shinyapps.io.

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bugfix.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/qc.md
- .github/ISSUE_TEMPLATE/ui.md
- .github/pull_request_template.md
Updated issue and PR templates to better match the sorts of issues I want to write (and to encourage links to addressed issues).
> Update issue/PR templates

- DESCRIPTION
- NEWS.md
- R/gsmApp_Server.R
- R/gsmApp_UI.R
- R/mod_MetricDetails_Server.R
- R/mod_ScatterPlot_UI.R
- man/htmlDependency_ScatterPlotInput.Rd
- man/htmlDependency_WidgetPlotInputHelpers.Rd
- tests/testthat/test-run_gsm_app.R
Final checks for v2.0.0.
- Closes #262.
> Prep for v2.0.0 release

- DESCRIPTION
Require gsm 2.1+ in DESCRIPTION.
> Require gsm 2.1+.

- DESCRIPTION
> Peg to gsm release tag.

- .github/workflows/pkgdown.yaml
- _pkgdown.yml
Copy pkgdown.yml from gsm, and delete the example-report-generation stuff.
- Closes #275
> Version from gsm.

- DESCRIPTION
- NEWS.md
Helpful for differentiating between prod and dev websites, etc.
> Increment dev version.

- README.Rmd
- README.md
Install `@*release` for prod. Also tweaked some wording around prod vs dev.
- Closes #279.
> Install latest tag.

- R/gsmApp_Server.R
- R/mod_GroupOverview_Server.R
- R/mod_StudyOverview_Server.R
- inst/htmlwidgets/Widget_GroupOverview.js
- inst/inputs/groupOverviewInput.js
- tests/testthat/test-mod_GroupOverview_Server.R
- tests/testthat/test-mod_StudyOverview_Server.R
- tests/testthat/test-run_gsm_app.R
Update GroupOverview module (and its upstream uses) so that all clicks in the Group Overview table cause updates, even if it's the "same" value.
- Closes #297.
> React to *all* clicks in Group Overview table.

- .github/ISSUE_TEMPLATE/plugin.md
- gsm.app.Rproj
No actual code changes, don't really need to wait for GHA.
- Closes #343.
> Add plugin issue template.

- .github/ISSUE_TEMPLATE/plugin.md
Quick addition. Making this as a PR just to avoid issues, will merge shortly.
> Tweaks to the plugin issue template to better reflect current usage.

- NEWS.md
- R/aaa-shared.R
- R/gsmApp_Server.R
- R/srvr_MetricDetails.R
- R/srvr_SyncInput.R
- man/shared-params.Rd
- man/srvr_SyncTab.Rd
Only hop to tabs when their linked input changes *and the user isn't already on an acceptable tab.*
- Closes #374.
> Better input/tab syncing

- DESCRIPTION
- NEWS.md
We'll have one more PR to merge this into main, but this is the pre-RC.
> Prepare for gsm.app 2.4.0 release.

- tests/testthat/test-run_gsm_app.R
I skipped some tests on CI because they were failing on CI but not in actual usage. I want to see if the chromote issues have worked their way through CI yet.
> Unskip tests?
